export type CaseType = "website" | "app" | "miniprogram" | "ai" | "all";
export type CaseIndustry = "ecommerce" | "education" | "enterprise" | "food" | "all";

export const CASE_TYPES = [
  { value: "all" as CaseType, label: "全部" },
  { value: "website" as CaseType, label: "网站搭建" },
  { value: "app" as CaseType, label: "APP 开发" },
  { value: "miniprogram" as CaseType, label: "微信小程序" },
  { value: "ai" as CaseType, label: "AI 工具" },
];

export const CASE_INDUSTRIES = [
  { value: "all" as CaseIndustry, label: "全部行业" },
  { value: "ecommerce" as CaseIndustry, label: "电商/零售" },
  { value: "education" as CaseIndustry, label: "教育/培训" },
  { value: "enterprise" as CaseIndustry, label: "企业/办公" },
  { value: "food" as CaseIndustry, label: "餐饮/生活服务" },
];

export interface CaseItem {
  id: string;
  title: string;
  type: CaseType;
  industry: CaseIndustry;
  clientBrief: string;
  solutionBrief: string;
  metrics: string[];
  /** 案例配图路径，如 "/images/cases/1.jpg"，图片放在 public/images/cases/ 下 */
  image?: string;
  featured?: boolean;
}

export const CASES_LIST: CaseItem[] = [
  {
    id: "1",
    title: "某家居品牌全渠道数字化",
    type: "miniprogram",
    industry: "ecommerce",
    clientBrief: "线下 50+ 门店，线上有天猫店，库存与订单分散",
    solutionBrief: "品牌小程序商城 + 全渠道中台（库存通/订单通/会员通）+ 门店自提",
    metrics: ["库存周转天数从 45 天降至 28 天", "双 11 订单量同比增 200%，系统 0 故障"],
    featured: true,
    image: "/images/cases/jiaju.jpg",
  },
  {
    id: "2",
    title: "某连锁茶饮数字化运营",
    type: "miniprogram",
    industry: "food",
    clientBrief: "区域连锁茶饮 20+ 门店，高峰排队久、会员难沉淀",
    solutionBrief: "小程序预点餐到店取餐 + 聚合收银 + 会员积分与优惠券 + 多门店数据看板",
    metrics: ["高峰等位时长平均缩短约 40%", "私域贡献订单占比超 35%"],
    featured: true,
    image: "/images/cases/liansuocha.jpg",
  },
  {
    id: "3",
    title: "某科技公司协同办公平台",
    type: "app",
    industry: "enterprise",
    clientBrief: "约 200 人多地办公，OA 与沟通工具分散，审批与考勤脱节",
    solutionBrief: "统一协同（IM+文档+会议）+ 审批考勤人事 + CRM 与项目协作 + SSO 与审计",
    metrics: ["移动审批占比超 80%", "考勤与人事、薪酬数据打通"],
    featured: true,
    image: "/images/cases/xietongpingtai.jpg",
  },
  {
    id: "4",
    title: "某品牌官网改版",
    type: "website",
    industry: "ecommerce",
    clientBrief: "品牌 DTC 转型，需官网承载流量与转化",
    solutionBrief: "响应式官网 + SEO 优化 + 转化率动线设计",
    metrics: ["上线 3 个月访问量提升 150%"],
    image: "/images/cases/pingpaiguanw.jpg",
  },
  {
    id: "5",
    title: "智慧旅游小程序",
    type: "miniprogram",
    industry: "ecommerce",
    clientBrief: "区域文旅，需吃住行游购娱一站式服务与核销",
    solutionBrief: "小程序预订与核销 + 多业态商户对接 + 营销活动",
    metrics: ["吃住行游购娱全链条覆盖", "扫码即可体验"],
    image: "/images/cases/zhihuilvy.jpg",
  },
  {
    id: "6",
    title: "企业协同 APP（跨端）",
    type: "app",
    industry: "enterprise",
    clientBrief: "需移动办公、审批与项目协作，iOS/Android 双端",
    solutionBrief: "uni-app 一套代码双端发布 + 协同与审批模块",
    metrics: ["跨端一套代码，维护成本大幅降低"],
    image: "/images/cases/qiyexietong.jpg",
  },
  {
    id: "7",
    title: "某职业培训机构在线平台",
    type: "website",
    industry: "education",
    clientBrief: "年招生约 5000 人，线下为主，线索转化与完课率难量化",
    solutionBrief: "官网与小程序招生 + 直播录播 + 教务排课与学员档案 + 数据看板",
    metrics: ["线索到付费转化率提升", "完课率与续费可追踪"],
    image: "/images/cases/zhiyepeixun.jpg",
  },
  {
    id: "8",
    title: "某零售企业智能推荐与补货",
    type: "ai",
    industry: "ecommerce",
    clientBrief: "SKU 多、人工补货与推荐效率低",
    solutionBrief: "智能推荐引擎 + 销售预测与补货建议",
    metrics: ["推荐点击率与补货准确度提升"],
    image: "/images/cases/lingshouqiye.jpg",
  },
  {
    id: "9",
    title: "某美妆品牌独立站与小程序双阵地",
    type: "website",
    industry: "ecommerce",
    clientBrief: "美妆品牌希望摆脱平台依赖，建立私域与 DTC 销售",
    solutionBrief: "品牌官网商城 + 微信小程序 + 会员积分与裂变",
    metrics: ["单客年消费额增长约 15%", "私域复购占比提升"],
    image: "/images/cases/meizhuang.jpg",
  },
  {
    id: "10",
    title: "某生鲜前置仓小程序与拣货系统",
    type: "miniprogram",
    industry: "food",
    clientBrief: "社区生鲜、前置仓模式，订单履约与拣货效率待提升",
    solutionBrief: "小程序商城 + 门店拣货系统 + 即时配送对接",
    metrics: ["订单履约率从 75% 提升至 92%"],
    image: "/images/cases/shengxian.jpg",
  },
  {
    id: "11",
    title: "某 K12 教培机构官网与试听转化",
    type: "website",
    industry: "education",
    clientBrief: "K12 学科辅导，希望官网获客与试听转化可追踪",
    solutionBrief: "官网课程展示 + 试听预约与留资 + 线索分配与跟进",
    metrics: ["留资到试听转化率提升", "获客成本下降"],
    image: "/images/cases/k12.jpg",
  },
  {
    id: "12",
    title: "某连锁餐饮多门店收银与会员通",
    type: "miniprogram",
    industry: "food",
    clientBrief: "连锁餐饮 30+ 店，收银与会员各店分散",
    solutionBrief: "小程序点餐/外卖 + 聚合收银 + 多门店会员通 + 数据看板",
    metrics: ["会员复购率提升", "总部可实时查看各店经营"],
    image: "/images/cases/shouyin.jpg",
  },
  {
    id: "13",
    title: "某制造企业移动办公与审批",
    type: "app",
    industry: "enterprise",
    clientBrief: "制造企业多地工厂，需移动审批与生产报工",
    solutionBrief: "移动办公 APP + 审批流程 + 生产报工与报表",
    metrics: ["审批平均处理时长缩短", "报工数据实时可查"],
    image: "/images/cases/yidongbangong.jpg",
  },
  {
    id: "14",
    title: "某知识付费训练营小程序",
    type: "miniprogram",
    industry: "education",
    clientBrief: "轻课与训练营，需裂变拉新与完课激励",
    solutionBrief: "小程序课程 + 打卡与社群 + 分销与拼团",
    metrics: ["完课率与复购率提升", "裂变获客成本降低"],
    image: "/images/cases/zhishifufei.jpg",
  },
  {
    id: "15",
    title: "某地产企业官网与留资系统",
    type: "website",
    industry: "enterprise",
    clientBrief: "地产项目需官网展示与留资、到访预约",
    solutionBrief: "响应式官网 + 留资表单与到访预约 + 线索分配",
    metrics: ["留资量提升", "到访转化可追踪"],
    image: "/images/cases/dichanqiye.jpg",
  },
  {
    id: "16",
    title: "某餐饮品牌外卖与到店一体化",
    type: "miniprogram",
    industry: "food",
    clientBrief: "单店/少量门店，希望外卖与到店统一运营",
    solutionBrief: "小程序点餐与外卖 + 排队取号 + 会员优惠券",
    metrics: ["等位时间缩短", "复购率提升"],
    image: "/images/cases/waimai.jpg",
  },
  {
    id: "17",
    title: "某跨境电商独立站与多平台订单",
    type: "website",
    industry: "ecommerce",
    clientBrief: "亚马逊卖家拓展独立站，需多平台订单统一与 AI 内容",
    solutionBrief: "独立站搭建 + 多平台订单统一管理 + AI 商品内容生成",
    metrics: ["错发率从 15% 降至接近零", "履约成本降低"],
    image: "/images/cases/kuajing.jpg",
  },
  {
    id: "18",
    title: "某集团企业统一门户与 SSO",
    type: "website",
    industry: "enterprise",
    clientBrief: "集团多法人多系统，需统一门户与单点登录",
    solutionBrief: "集团门户 + SSO 与权限 + 与现有系统对接",
    metrics: ["登录与权限统一", "满足等保与审计要求"],
    image: "/images/cases/qiyetongyi.jpg",
  },
  {
    id: "19",
    title: "某健身/瑜伽馆预约与会员次卡",
    type: "miniprogram",
    industry: "food",
    clientBrief: "健身/瑜伽馆需预约、次卡与会员管理",
    solutionBrief: "小程序预约与排课 + 会员次卡/储值 + 核销与统计",
    metrics: ["预约到店率提升", "会员留存与升单更清晰"],
    image: "/images/cases/jianshen.jpg",
  },
  {
    id: "20",
    title: "AI 客服与智能问答落地",
    type: "ai",
    industry: "ecommerce",
    clientBrief: "客服咨询量大，希望 7×24 自动回复与转人工",
    solutionBrief: "大模型接入 + 知识库与 FAQ + 智能问答与转人工",
    metrics: ["常见问题自动回复占比提升", "人工客服压力下降"],
    image: "/images/cases/aiyuzhineng.jpg",
  },
  {
    id: "21",
    title: "某 SaaS 产品官网与文档站",
    type: "website",
    industry: "enterprise",
    clientBrief: "SaaS 产品需官网与产品文档、帮助中心",
    solutionBrief: "官网与产品页 + 文档站/帮助中心 + SEO",
    metrics: ["搜索流量与文档查阅量提升"],
    image: "/images/cases/saas.jpg",
  },
  {
    id: "22",
    title: "某本地生活服务平台小程序",
    type: "miniprogram",
    industry: "food",
    clientBrief: "本地生活服务聚合，需多商户入驻与核销",
    solutionBrief: "小程序多商户入驻 + 订单与核销 + 分账与结算",
    metrics: ["商户与订单量增长", "核销与结算自动化"],
    image: "/images/cases/shenghuo.jpg",
  },
];
