export type BlogCategory = "tech" | "industry" | "changelog" | "all";

export const BLOG_CATEGORIES = [
  { value: "all" as BlogCategory, label: "全部" },
  { value: "tech" as BlogCategory, label: "技术博客" },
  { value: "industry" as BlogCategory, label: "行业洞察" },
  { value: "changelog" as BlogCategory, label: "更新日志" },
];

export interface BlogPost {
  id: string;
  title: string;
  category: BlogCategory;
  date: string;
  excerpt: string;
  author?: string;
  /** 外部文章链接（掘金/CSDN 等），存在则点击跳转原文 */
  externalUrl?: string;
  /** 来源标识，用于展示「阅读原文」等 */
  source?: "juejin" | "csdn";
}

export const BLOG_POSTS: BlogPost[] = [
  // ---------- 技术博客（含掘金/CSDN 优质文章引用） ----------
  {
    id: "1",
    title: "Vue.js：响应式系统与数据双向绑定的奥秘",
    category: "tech",
    date: "2024-12",
    excerpt: "深入讲解 Vue 的响应式机制与数据双向绑定原理，包括 Observer、Dep、Watcher 等核心概念，以及 v-model 的实现与性能优化技巧。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7412672656364372031",
  },
  {
    id: "2",
    title: "2024 年前端性能优化：Vue3 与 Vite 项目全方位攻略",
    category: "tech",
    date: "2024-11",
    excerpt: "系统讲解前端性能优化策略：减少 HTTP 请求、图片懒加载、缓存策略、浏览器缓存等，针对 Vue3 + Vite 大型项目的实战场景。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7452518173184901160",
  },
  {
    id: "3",
    title: "Vue 生态系统（2024 版本）完整指南",
    category: "tech",
    date: "2024-10",
    excerpt: "全面介绍 Vue 生态：Vite 构建、Nuxt 元框架、Vue Router、Pinia 状态管理，以及 TanStack Query、XState 等社区方案，快速了解最新开发生态。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7367667831200890919",
  },
  {
    id: "4",
    title: "uni-app 跨端实战：一套代码适配 H5 / 小程序 / APP 的避坑指南",
    category: "tech",
    date: "2024-09",
    excerpt: "条件编译、rpx 适配、导航栏与安全区、登录/支付/文件上传在各端差异处理，以及 HBuilderX 调试与 NVUE 性能优化实践。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7374297192129314855",
  },
  {
    id: "5",
    title: "uni-app 跨端开发之疑难杂症（持续更新）",
    category: "tech",
    date: "2022-10",
    excerpt: "跨端三剑客对比、条件编译 #ifdef/#ifndef、框架层编译时适配、样式兼容与真机网络调试等实战经验总结。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7156017191169556511",
  },
  {
    id: "6",
    title: "基于 SpringBoot + Vue 前后端分离的博客系统实现",
    category: "tech",
    date: "2024-08",
    excerpt: "Spring Boot 3.x、Spring Security + JWT、MyBatis-Plus、Vue 3 + Vite + Pinia，RESTful API 设计与前端状态管理实战。",
    source: "csdn",
    externalUrl: "https://blog.csdn.net/2501_93834392/article/details/153582631",
  },
  {
    id: "7",
    title: "评论系统的全栈设计思路：从数据模型到接口实现",
    category: "tech",
    date: "2024-07",
    excerpt: "Vue3 + TypeScript 前端与 Express 后端，评论系统数据模型、分页与逻辑删除，完整全栈项目设计与 GitHub 开源实现。",
    source: "csdn",
    externalUrl: "https://blog.csdn.net/weixin_41196185/article/details/140493080",
  },
  {
    id: "8",
    title: "UniCloud 个人全栈项目实践",
    category: "tech",
    date: "2020-10",
    excerpt: "UniApp + UniCloud 全栈方案：响应式官网、登录注册、文件上传、多表查询、即时通信、OSS 与短信验证码等完整业务逻辑。",
    source: "csdn",
    externalUrl: "https://blog.csdn.net/weixin_44601948/article/details/109111604",
  },
  {
    id: "9",
    title: "电商全渠道中台：库存通与订单通的架构设计",
    category: "tech",
    date: "2025-01-28",
    excerpt: "如何设计库存通、订单通与会员通，支撑线上线下融合与高并发大促。",
    author: "极造极技术团队",
  },
  {
    id: "10",
    title: "大规模时序数据存储与查询实践",
    category: "tech",
    date: "2025-02-10",
    excerpt: "分享在千万级指标场景下的存储选型、索引设计与查询优化经验，兼顾写入吞吐与查询延迟。",
    author: "极造极技术团队",
  },
  {
    id: "15",
    title: "本地使用 Docker Compose 部署 Next.js + Monorepo 项目",
    category: "tech",
    date: "2024-12",
    excerpt: "使用 pnpm workspaces 与 Docker Compose 构建 Next.js + monorepo 多应用与共享包，从项目结构到部署流程。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7412672713377005631",
  },
  {
    id: "16",
    title: "微信小程序开发从 0 到 1（原生开发者工具）",
    category: "tech",
    date: "2022-04",
    excerpt: "从零开始：.json/.wxml/.wxss/.js 四类文件、app.json 配置、微信开发者工具与基础项目结构，建立全局认识。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7081539399255195655",
  },
  {
    id: "17",
    title: "实战：「小打卡」小程序从创意到上线完整开发解析",
    category: "tech",
    date: "2019-08",
    excerpt: "准备工具（脑图、墨刀、ShowDoc、Postman）、模块划分、原型设计、前后端联调与 weui-wxss 组件库，完整项目流程。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/6844903480289656839",
  },
  {
    id: "18",
    title: "嘿，别想那么复杂！我的第一个微信小程序长这样",
    category: "tech",
    date: "2024-10",
    excerpt: "从零搭建第一个微信小程序的思路与步骤，简化认知、快速上手，适合入门与练手。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7555698052482940966",
  },
  {
    id: "19",
    title: "通过微信小程序实现「钉钉打卡」：外勤考勤实战",
    category: "tech",
    date: "2019-09",
    excerpt: "wx.getLocation/chooseLocation、MD5 防刷、自拍验证、签到/签退配对与地理范围限制，一天多次外勤打卡方案。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/6844904134991151111",
  },
  {
    id: "20",
    title: "端侧模型集成方案与性能优化实践",
    category: "tech",
    date: "2024-11",
    excerpt: "在 Web/Chrome 扩展中集成轻量级 AI 模型：ONNX.js/TensorFlow.js、embedding 与 RAG 检索，端侧推理与隐私保护。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7507840946039390218",
  },
  {
    id: "21",
    title: "前端与 AI 融合共生：重构前端能力边界",
    category: "tech",
    date: "2024-12",
    excerpt: "开发侧（代码生成、测试）、产品侧（AIGC、推荐）、技术侧（AI 组件、流式渲染）、运维侧（监控、灰度）的融合实践。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7602900131540647977",
  },
  {
    id: "22",
    title: "Vue3 怎么和大模型交互？",
    category: "tech",
    date: "2024-09",
    excerpt: "使用 OpenAI SDK 实现流式对话、markdown-it 渲染与上下文管理，Vue3 接入大模型对话的完整示例。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7481167019645648905",
  },
  {
    id: "23",
    title: "Next.js 全栈实战：用向量引擎重构 AI 网关，GPT-4 响应提升 300%",
    category: "tech",
    date: "2024-12",
    excerpt: "向量引擎优化 API 网关、多模型聚合、流式响应与避坑指南，附源码与性能对比。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7601077290682056756",
  },
  {
    id: "24",
    title: "使用 Next.js 构建 AI 对话页面",
    category: "tech",
    date: "2024-08",
    excerpt: "Next.js + 智谱 GLM-4-Flash 模型搭建对话页：流式输出、会话管理与前端联调实践。",
    source: "juejin",
    externalUrl: "https://juejin.cn/post/7431580770214543375",
  },
  {
    id: "25",
    title: "Vue3 + Node.js + MySQL 写接口（一）",
    category: "tech",
    date: "2024-07",
    excerpt: "三端项目：后台管理、Web 展示与数据库，用户/新闻模块、Express 后端与 Element Plus 前端。",
    source: "csdn",
    externalUrl: "https://blog.csdn.net/qq_44930306/article/details/149073777",
  },
  {
    id: "26",
    title: "前后端分离：Vue + NodeJS(Koa) + MongoDB 从产品到开发",
    category: "tech",
    date: "2024-09",
    excerpt: "全栈实践：Koa 后端、MongoDB 与 Vue 前端，从产品设计到接口与状态管理的完整流程。",
    source: "csdn",
    externalUrl: "https://blog.csdn.net/androidstarjack/article/details/133917671",
  },
  {
    id: "27",
    title: "基于 Node.js + Vue 的全栈项目实战",
    category: "tech",
    date: "2024-08",
    excerpt: "Express + Vue、MySQL 与前后端分离架构，从接口设计到前端调用的完整项目示例。",
    source: "csdn",
    externalUrl: "https://blog.csdn.net/QQ_511008285/article/details/133690210",
  },
  {
    id: "28",
    title: "TypeScript 在前后端一体化中的实践",
    category: "tech",
    date: "2025-01-15",
    excerpt: "共享类型定义、接口契约与校验，前后端同仓或 Monorepo 下的 TypeScript 协作与提效。",
    author: "极造极技术团队",
  },
  {
    id: "29",
    title: "小程序性能优化清单：首屏与分包",
    category: "tech",
    date: "2025-01-08",
    excerpt: "首屏渲染、分包加载、图片与请求优化，以及 setData 与长列表的注意点，提升小程序流畅度。",
    author: "极造极技术团队",
  },
  // ---------- 行业洞察 ----------
  {
    id: "11",
    title: "2025 年零售数字化趋势：全域融合与 AI 驱动",
    category: "industry",
    date: "2025-01-20",
    excerpt: "从全域融合、私域运营到 AI 推荐与内容生成，零售数字化正在发生的变化。",
  },
  {
    id: "12",
    title: "教培行业数字化：从招生到交付的闭环",
    category: "industry",
    date: "2025-01-12",
    excerpt: "教培机构如何通过官网、小程序与数据看板，提升获客、完课率与续费。",
  },
  {
    id: "30",
    title: "企业数字化选型指南：自建 vs 采购 vs 定制",
    category: "industry",
    date: "2025-01-25",
    excerpt: "从业务规模、预算与周期出发，如何选择自建团队、采购 SaaS 或定制开发，以及混合模式的适用场景。",
  },
  {
    id: "31",
    title: "2025 年小程序生态观察：多端与私域",
    category: "industry",
    date: "2025-01-18",
    excerpt: "微信/支付宝/抖音等多端并存、私域运营与公域引流，小程序在零售与生活服务中的趋势。",
  },
  {
    id: "32",
    title: "餐饮数字化：从点餐到会员的 ROI 怎么算",
    category: "industry",
    date: "2025-01-05",
    excerpt: "小程序点餐、外卖对接与会员营销的投入与回报测算，以及多门店数据看板对决策的支撑。",
  },
  // ---------- 更新日志 ----------
  {
    id: "13",
    title: "产品更新：智能数据平台 2.0 发布",
    category: "changelog",
    date: "2025-02-10",
    excerpt: "全新架构、实时计算与 AI 增强分析能力全面升级，助力企业数据驱动决策。",
  },
  {
    id: "14",
    title: "入选「年度最具成长性数据服务商」",
    category: "changelog",
    date: "2025-01-28",
    excerpt: "由行业权威机构评选，肯定我们在数据智能与客户价值上的持续投入。",
  },
  {
    id: "33",
    title: "资源中心上线：技术博客与行业洞察",
    category: "changelog",
    date: "2025-02-14",
    excerpt: "资源中心正式上线，聚合技术博客、行业洞察与更新日志，持续输出专业内容。",
  },
  {
    id: "34",
    title: "解决方案页完善：电商/教育/餐饮/企业",
    category: "changelog",
    date: "2025-02-12",
    excerpt: "四大行业解决方案页面完善，覆盖架构、模块、场景与案例，支持按行业获取方案。",
  },
];
